### ISSUE TITLE
Game Editor status is always "Unknow"

### ISSUE THREAD

**Issue by NCSGeek** [ProjectCeleste/Celeste_Launcher#23]
The status of the editor is always "Unknow".
![screenshot_2](https://user-images.githubusercontent.com/18708328/39678720-8b54ba84-515f-11e8-8e57-02741d9109e9.png)

I launched it right after this screenshot, and I clicked "Install" before taking the screenshot.

**Comment by Ryddag** [comment]
this bug is already fixed, the fix will be deployed with next update.
