### ISSUE TITLE
SocketException 0x80004005 when starting the launcher

### ISSUE THREAD

**Issue by dirkduplooy** [ProjectCeleste/Celeste_Launcher#54]
# Describe the bug

Celeste_Launcher_Gui.exe does not execute and simply exit

## Steps to reproduce

Launch from  Celest_Launcher_Guiexe

## Expected behavior

Should run. Prints `System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions` in the log.
[launcherlog20200114.log](https://github.com/ProjectCeleste/Celeste_Launcher/files/4059218/launcherlog20200114.log)

**Comment by dirkduplooy** [comment]
I did open the firewall, so that is not the issue

**Comment by dirkduplooy** [comment]
Beta 1 works like a charm overwrite 3.0.2.1 and it launches

**Comment by martinmine** [comment]
Hi, thanks for reporting this. Are you running any other firewall other than the Windows firewall on your machine? A firewall rule should regardless not lead to the launcher crashing so I don't think that is related to this issue.

**Comment by dirkduplooy** [comment]
Hi it was not the firewall, but I saw it in the log, even after I gave the launcher permission it failed if there are any other logs files I can send I am more than willing

**Comment by martinmine** [comment]
@dirkduplooy Thanks, I really want to know why this occurs on your machine as it is not making any sense from how I see it. There are unfortunately no other logs to my knowledge. However, would you let me know some things about your machine such as:
- Operating system (which specific edition/version)
- Installed anti-virus or other security software/solutions
- If your machine is part of an organization or set up for home/commercial usage (I'm thinking if there could be any group policy rules preventing the launcher from connecting)

**Comment by martinmine** [comment]
I'm also fine if you send me some of this info on Discord or Twitter DM if you are not comfortable providing this information publicly.

**Comment by martinmine** [comment]
> Beta 1 works like a charm overwrite 3.0.2.1 and it launches
Can you perhaps elaborate a bit? Did the beta 2 launcher throw this exception, while overwriting the beta 1 launcher with the beta 2 allow it to launch?

**Comment by dirkduplooy** [comment]
Hi martinemine, I overwrite the beta 2 files with those of beta 1. I send a msg in Discord with the Github Description and Bug nr, think it will work better

**Comment by martinmine** [comment]
The issue in this case was that a 3rd party firewall was preventing outgoing connections. With the changes in the last build the assembly name and binary file name became changed due to build infrastructure changes. 

People receiving this error message should check if they have a strict firewall set up to update the rules when installing new versions of the launcher.
