### ISSUE TITLE
Minor Visual Inconsistencies and Anti-Virus Problems

### ISSUE THREAD

**Issue by Axel231** [ProjectCeleste/Celeste_Launcher#7]
1. The new Celeste client is being detected as a Trojan by my anti-virus program "Microsoft Security essentials".  (I know it means nothing, and I've allowed it through but I don't think you would want it being detected as a virus at all)

2. There are a couple of visual inconsistencies with the Celeste launcher, while using Windows 7 with the Display settings set to increase the text by 125%

3. There is a bracket missing in the second screen of the launcher : "Pending Friends Request (0"
compared to "Pending Friends Invite (0)"

4. Just a personal preference but I would like capitalization of the the letter "f" in "false" next to Banned and Connected, for consistency with the rest of the words and layout of the launcher

5. It's slightly confusing that you can select which civilization you want from the drop box, even though both are available when the game is actually launched regardless of which you chose in the Celeste launcher.

(thank you for your hard work :+1: )

![7mb file](https://user-images.githubusercontent.com/29547567/27293979-e56c903e-550f-11e7-8f27-cb825e8e4605.png)

![celeste](https://user-images.githubusercontent.com/29547567/27294060-307b4bba-5510-11e7-9c31-ccdbafb73be2.png)

**Comment by IAsAbovesoBelowI** [comment]
https://www.instructables.com/answers/Why-is-my-C-program-detected-as-a-virus/

thought this might help.
